/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * AstraCore Space Mission Simulation & Control Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface LoginBody {
  username: string;
  password: string;
}

export type RegisterBodyRole =
  (typeof RegisterBodyRole)[keyof typeof RegisterBodyRole];

export const RegisterBodyRole = {
  admin: "admin",
  user: "user",
} as const;

export interface RegisterBody {
  username: string;
  email: string;
  password: string;
  role?: RegisterBodyRole;
}

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const UserRole = {
  admin: "admin",
  user: "user",
} as const;

export interface User {
  id: number;
  username: string;
  email: string;
  role: UserRole;
  createdAt: string;
}

export interface AuthResponse {
  token: string;
  user: User;
}

export type MissionStatus = (typeof MissionStatus)[keyof typeof MissionStatus];

export const MissionStatus = {
  planning: "planning",
  active: "active",
  completed: "completed",
  failed: "failed",
  aborted: "aborted",
} as const;

export interface Mission {
  id: number;
  name: string;
  destination: string;
  launchDate: string;
  payload: string;
  status: MissionStatus;
  description?: string;
  userId: number;
  successProbability?: number;
  createdAt: string;
}

export interface CreateMissionBody {
  name: string;
  destination: string;
  launchDate: string;
  payload: string;
  description?: string;
}

export type UpdateMissionBodyStatus =
  (typeof UpdateMissionBodyStatus)[keyof typeof UpdateMissionBodyStatus];

export const UpdateMissionBodyStatus = {
  planning: "planning",
  active: "active",
  completed: "completed",
  failed: "failed",
  aborted: "aborted",
} as const;

export interface UpdateMissionBody {
  name?: string;
  status?: UpdateMissionBodyStatus;
  payload?: string;
  description?: string;
}

export interface DeleteResult {
  success: boolean;
}

export type AlertType = (typeof AlertType)[keyof typeof AlertType];

export const AlertType = {
  solar_storm: "solar_storm",
  signal_loss: "signal_loss",
  overheating: "overheating",
  fuel_low: "fuel_low",
  system_failure: "system_failure",
  collision_risk: "collision_risk",
} as const;

export type AlertSeverity = (typeof AlertSeverity)[keyof typeof AlertSeverity];

export const AlertSeverity = {
  critical: "critical",
  warning: "warning",
  safe: "safe",
} as const;

export interface Alert {
  id: number;
  type: AlertType;
  severity: AlertSeverity;
  message: string;
  acknowledged: boolean;
  missionId?: number;
  createdAt: string;
}

export type CreateAlertBodyType =
  (typeof CreateAlertBodyType)[keyof typeof CreateAlertBodyType];

export const CreateAlertBodyType = {
  solar_storm: "solar_storm",
  signal_loss: "signal_loss",
  overheating: "overheating",
  fuel_low: "fuel_low",
  system_failure: "system_failure",
  collision_risk: "collision_risk",
} as const;

export type CreateAlertBodySeverity =
  (typeof CreateAlertBodySeverity)[keyof typeof CreateAlertBodySeverity];

export const CreateAlertBodySeverity = {
  critical: "critical",
  warning: "warning",
  safe: "safe",
} as const;

export interface CreateAlertBody {
  type: CreateAlertBodyType;
  severity: CreateAlertBodySeverity;
  message: string;
  missionId?: number;
}

export interface AnalyticsSummary {
  totalMissions: number;
  activeMissions: number;
  successRate: number;
  totalAlerts: number;
  criticalAlerts: number;
  systemHealthScore: number;
  totalUsers: number;
}

export interface StatusCount {
  status: string;
  count: number;
}

export interface DestinationCount {
  destination: string;
  count: number;
}

export interface TimelinePoint {
  date: string;
  critical: number;
  warning: number;
  safe: number;
}

export type SystemHealthThrusterStatus =
  (typeof SystemHealthThrusterStatus)[keyof typeof SystemHealthThrusterStatus];

export const SystemHealthThrusterStatus = {
  nominal: "nominal",
  degraded: "degraded",
  critical: "critical",
  offline: "offline",
} as const;

export interface SystemHealth {
  id: number;
  fuelLevel: number;
  temperature: number;
  battery: number;
  signalStrength: number;
  oxygenLevel: number;
  thrusterStatus: SystemHealthThrusterStatus;
  timestamp: string;
}

export interface PredictBody {
  missionId?: number;
  destination: string;
  launchDate?: string;
  payload: string;
  fuelLevel?: number;
  crewSize?: number;
}

export type PredictionRiskLevel =
  (typeof PredictionRiskLevel)[keyof typeof PredictionRiskLevel];

export const PredictionRiskLevel = {
  low: "low",
  medium: "medium",
  high: "high",
  critical: "critical",
} as const;

export interface Prediction {
  id: number;
  missionId?: number;
  missionName?: string;
  successProbability: number;
  riskLevel: PredictionRiskLevel;
  riskFactors: string[];
  recommendation: string;
  confidence: number;
  createdAt: string;
}

export type NewsArticleCategory =
  (typeof NewsArticleCategory)[keyof typeof NewsArticleCategory];

export const NewsArticleCategory = {
  nasa: "nasa",
  isro: "isro",
  spacex: "spacex",
  esa: "esa",
  general: "general",
} as const;

export interface NewsArticle {
  id: number;
  title: string;
  summary: string;
  source: string;
  url?: string;
  imageUrl?: string;
  publishedAt: string;
  category: NewsArticleCategory;
}

export type CommunicationBodyMessageType =
  (typeof CommunicationBodyMessageType)[keyof typeof CommunicationBodyMessageType];

export const CommunicationBodyMessageType = {
  text: "text",
  telemetry: "telemetry",
  command: "command",
  emergency: "emergency",
} as const;

export interface CommunicationBody {
  destination: string;
  messageType: CommunicationBodyMessageType;
  message?: string;
}

export type CommunicationResultStatus =
  (typeof CommunicationResultStatus)[keyof typeof CommunicationResultStatus];

export const CommunicationResultStatus = {
  transmitted: "transmitted",
  delayed: "delayed",
  lost: "lost",
} as const;

export interface CommunicationResult {
  destination: string;
  distanceKm: number;
  oneWayDelaySeconds: number;
  roundTripDelaySeconds: number;
  signalStrength: number;
  status: CommunicationResultStatus;
  message?: string;
}

export type ListMissionsParams = {
  status?: ListMissionsStatus;
  destination?: string;
};

export type ListMissionsStatus =
  (typeof ListMissionsStatus)[keyof typeof ListMissionsStatus];

export const ListMissionsStatus = {
  planning: "planning",
  active: "active",
  completed: "completed",
  failed: "failed",
  aborted: "aborted",
} as const;

export type ListAlertsParams = {
  severity?: ListAlertsSeverity;
  acknowledged?: boolean;
};

export type ListAlertsSeverity =
  (typeof ListAlertsSeverity)[keyof typeof ListAlertsSeverity];

export const ListAlertsSeverity = {
  critical: "critical",
  warning: "warning",
  safe: "safe",
} as const;
