/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * AstraCore Space Mission Simulation & Control Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Authenticate user and get JWT token
 */
export const LoginBody = zod.object({
  username: zod.string(),
  password: zod.string(),
});

export const LoginResponse = zod.object({
  token: zod.string(),
  user: zod.object({
    id: zod.number(),
    username: zod.string(),
    email: zod.string(),
    role: zod.enum(["admin", "user"]),
    createdAt: zod.coerce.date(),
  }),
});

/**
 * @summary Register a new user
 */
export const registerBodyRoleDefault = `user`;

export const RegisterBody = zod.object({
  username: zod.string(),
  email: zod.string(),
  password: zod.string(),
  role: zod.enum(["admin", "user"]).default(registerBodyRoleDefault),
});

/**
 * @summary Get current authenticated user
 */
export const GetMeResponse = zod.object({
  id: zod.number(),
  username: zod.string(),
  email: zod.string(),
  role: zod.enum(["admin", "user"]),
  createdAt: zod.coerce.date(),
});

/**
 * @summary List all missions
 */
export const ListMissionsQueryParams = zod.object({
  status: zod
    .enum(["planning", "active", "completed", "failed", "aborted"])
    .optional(),
  destination: zod.coerce.string().optional(),
});

export const ListMissionsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  destination: zod.string(),
  launchDate: zod.coerce.date(),
  payload: zod.string(),
  status: zod.enum(["planning", "active", "completed", "failed", "aborted"]),
  description: zod.string().optional(),
  userId: zod.number(),
  successProbability: zod.number().optional(),
  createdAt: zod.coerce.date(),
});
export const ListMissionsResponse = zod.array(ListMissionsResponseItem);

/**
 * @summary Create a new mission
 */
export const CreateMissionBody = zod.object({
  name: zod.string(),
  destination: zod.string(),
  launchDate: zod.coerce.date(),
  payload: zod.string(),
  description: zod.string().optional(),
});

/**
 * @summary Get a mission by ID
 */
export const GetMissionParams = zod.object({
  id: zod.coerce.number(),
});

export const GetMissionResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  destination: zod.string(),
  launchDate: zod.coerce.date(),
  payload: zod.string(),
  status: zod.enum(["planning", "active", "completed", "failed", "aborted"]),
  description: zod.string().optional(),
  userId: zod.number(),
  successProbability: zod.number().optional(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update mission status or details
 */
export const UpdateMissionParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateMissionBody = zod.object({
  name: zod.string().optional(),
  status: zod
    .enum(["planning", "active", "completed", "failed", "aborted"])
    .optional(),
  payload: zod.string().optional(),
  description: zod.string().optional(),
});

export const UpdateMissionResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  destination: zod.string(),
  launchDate: zod.coerce.date(),
  payload: zod.string(),
  status: zod.enum(["planning", "active", "completed", "failed", "aborted"]),
  description: zod.string().optional(),
  userId: zod.number(),
  successProbability: zod.number().optional(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete a mission
 */
export const DeleteMissionParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteMissionResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary List all system alerts
 */
export const ListAlertsQueryParams = zod.object({
  severity: zod.enum(["critical", "warning", "safe"]).optional(),
  acknowledged: zod.coerce.boolean().optional(),
});

export const ListAlertsResponseItem = zod.object({
  id: zod.number(),
  type: zod.enum([
    "solar_storm",
    "signal_loss",
    "overheating",
    "fuel_low",
    "system_failure",
    "collision_risk",
  ]),
  severity: zod.enum(["critical", "warning", "safe"]),
  message: zod.string(),
  acknowledged: zod.boolean(),
  missionId: zod.number().optional(),
  createdAt: zod.coerce.date(),
});
export const ListAlertsResponse = zod.array(ListAlertsResponseItem);

/**
 * @summary Create a new alert
 */
export const CreateAlertBody = zod.object({
  type: zod.enum([
    "solar_storm",
    "signal_loss",
    "overheating",
    "fuel_low",
    "system_failure",
    "collision_risk",
  ]),
  severity: zod.enum(["critical", "warning", "safe"]),
  message: zod.string(),
  missionId: zod.number().optional(),
});

/**
 * @summary Acknowledge an alert
 */
export const AcknowledgeAlertParams = zod.object({
  id: zod.coerce.number(),
});

export const AcknowledgeAlertResponse = zod.object({
  id: zod.number(),
  type: zod.enum([
    "solar_storm",
    "signal_loss",
    "overheating",
    "fuel_low",
    "system_failure",
    "collision_risk",
  ]),
  severity: zod.enum(["critical", "warning", "safe"]),
  message: zod.string(),
  acknowledged: zod.boolean(),
  missionId: zod.number().optional(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Get dashboard summary stats
 */
export const GetAnalyticsSummaryResponse = zod.object({
  totalMissions: zod.number(),
  activeMissions: zod.number(),
  successRate: zod.number(),
  totalAlerts: zod.number(),
  criticalAlerts: zod.number(),
  systemHealthScore: zod.number(),
  totalUsers: zod.number(),
});

/**
 * @summary Mission count grouped by status
 */
export const GetMissionsByStatusResponseItem = zod.object({
  status: zod.string(),
  count: zod.number(),
});
export const GetMissionsByStatusResponse = zod.array(
  GetMissionsByStatusResponseItem,
);

/**
 * @summary Mission count grouped by destination
 */
export const GetMissionsByDestinationResponseItem = zod.object({
  destination: zod.string(),
  count: zod.number(),
});
export const GetMissionsByDestinationResponse = zod.array(
  GetMissionsByDestinationResponseItem,
);

/**
 * @summary Alerts over last 7 days
 */
export const GetAlertsTimelineResponseItem = zod.object({
  date: zod.string(),
  critical: zod.number(),
  warning: zod.number(),
  safe: zod.number(),
});
export const GetAlertsTimelineResponse = zod.array(
  GetAlertsTimelineResponseItem,
);

/**
 * @summary Get current system health metrics
 */
export const GetSystemHealthResponse = zod.object({
  id: zod.number(),
  fuelLevel: zod.number(),
  temperature: zod.number(),
  battery: zod.number(),
  signalStrength: zod.number(),
  oxygenLevel: zod.number(),
  thrusterStatus: zod.enum(["nominal", "degraded", "critical", "offline"]),
  timestamp: zod.coerce.date(),
});

/**
 * @summary Get system health history (last 24 readings)
 */
export const GetSystemHealthHistoryResponseItem = zod.object({
  id: zod.number(),
  fuelLevel: zod.number(),
  temperature: zod.number(),
  battery: zod.number(),
  signalStrength: zod.number(),
  oxygenLevel: zod.number(),
  thrusterStatus: zod.enum(["nominal", "degraded", "critical", "offline"]),
  timestamp: zod.coerce.date(),
});
export const GetSystemHealthHistoryResponse = zod.array(
  GetSystemHealthHistoryResponseItem,
);

/**
 * @summary Get AI prediction for a mission
 */
export const GetPredictionBody = zod.object({
  missionId: zod.number().optional(),
  destination: zod.string(),
  launchDate: zod.coerce.date().optional(),
  payload: zod.string(),
  fuelLevel: zod.number().optional(),
  crewSize: zod.number().optional(),
});

export const GetPredictionResponse = zod.object({
  id: zod.number(),
  missionId: zod.number().optional(),
  missionName: zod.string().optional(),
  successProbability: zod.number(),
  riskLevel: zod.enum(["low", "medium", "high", "critical"]),
  riskFactors: zod.array(zod.string()),
  recommendation: zod.string(),
  confidence: zod.number(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary List recent AI predictions
 */
export const ListPredictionsResponseItem = zod.object({
  id: zod.number(),
  missionId: zod.number().optional(),
  missionName: zod.string().optional(),
  successProbability: zod.number(),
  riskLevel: zod.enum(["low", "medium", "high", "critical"]),
  riskFactors: zod.array(zod.string()),
  recommendation: zod.string(),
  confidence: zod.number(),
  createdAt: zod.coerce.date(),
});
export const ListPredictionsResponse = zod.array(ListPredictionsResponseItem);

/**
 * @summary Get latest space news articles
 */
export const GetSpaceNewsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  summary: zod.string(),
  source: zod.string(),
  url: zod.string().optional(),
  imageUrl: zod.string().optional(),
  publishedAt: zod.coerce.date(),
  category: zod.enum(["nasa", "isro", "spacex", "esa", "general"]),
});
export const GetSpaceNewsResponse = zod.array(GetSpaceNewsResponseItem);

/**
 * @summary Simulate communication delay for a destination
 */
export const SimulateCommunicationBody = zod.object({
  destination: zod.string(),
  messageType: zod.enum(["text", "telemetry", "command", "emergency"]),
  message: zod.string().optional(),
});

export const SimulateCommunicationResponse = zod.object({
  destination: zod.string(),
  distanceKm: zod.number(),
  oneWayDelaySeconds: zod.number(),
  roundTripDelaySeconds: zod.number(),
  signalStrength: zod.number(),
  status: zod.enum(["transmitted", "delayed", "lost"]),
  message: zod.string().optional(),
});

/**
 * @summary List all users (admin only)
 */
export const ListUsersResponseItem = zod.object({
  id: zod.number(),
  username: zod.string(),
  email: zod.string(),
  role: zod.enum(["admin", "user"]),
  createdAt: zod.coerce.date(),
});
export const ListUsersResponse = zod.array(ListUsersResponseItem);
